version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: sistema_crt
      POSTGRES_USER: crt_user
      POSTGRES_PASSWORD: crt_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - crt_network

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://crt_user:crt_password@postgres:5432/sistema_crt
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      NODE_ENV: development
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
      - uploads:/app/uploads
    networks:
      - crt_network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:3001
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - crt_network

volumes:
  postgres_data:
  uploads:

networks:
  crt_network:
    driver: bridge